sonar.projectKey=ERP-MERN_Backend
sonar.projectName=ERP MERN Backend
sonar.sources=src
sonar.exclusions=**/node_modules/**
sonar.sourceEncoding=UTF-8
sonar.organization=hassen-2026
sonar.host.url=https://sonarcloud.io